# Generated by Django 4.2.7 on 2023-11-19 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, verbose_name='Codigo')),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo')),
                ('capacidad', models.PositiveIntegerField(verbose_name='Capacidad')),
                ('valor', models.FloatField(max_length=50, verbose_name='Valor')),
            ],
        ),
    ]
