# Generated by Django 4.2.7 on 2023-11-19 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0003_hab_delete_habitacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hab',
            name='descripcion',
            field=models.CharField(max_length=50, verbose_name='descripcion'),
        ),
        migrations.AlterField(
            model_name='hab',
            name='estado',
            field=models.CharField(max_length=50, verbose_name='estado'),
        ),
    ]
