# Generated by Django 4.2.7 on 2023-11-19 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0004_alter_hab_descripcion_alter_hab_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hab',
            name='id',
        ),
        migrations.AlterField(
            model_name='hab',
            name='nro_hab',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='numero'),
        ),
    ]
