# Generated by Django 4.2.7 on 2023-11-19 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0005_remove_hab_id_alter_hab_nro_hab'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_hab', models.CharField(max_length=50, verbose_name='numero')),
                ('codigo', models.CharField(max_length=50, verbose_name='codigo')),
                ('estado', models.CharField(max_length=50, verbose_name='estado')),
                ('descripcion', models.CharField(max_length=50, verbose_name='descripcion')),
            ],
        ),
        migrations.DeleteModel(
            name='Hab',
        ),
    ]
