# Generated by Django 4.2.7 on 2023-11-19 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0010_alter_tipo_habitacion_capacidad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hab',
            fields=[
                ('codigo', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='codigo')),
                ('nro_hab', models.CharField(max_length=50, verbose_name='numero')),
                ('tipo', models.CharField(max_length=50, verbose_name='tipo')),
                ('capacidad', models.IntegerField(verbose_name='capacidad')),
                ('valor', models.FloatField(verbose_name='valor')),
                ('estado', models.CharField(max_length=50, verbose_name='estado')),
                ('descripcion', models.CharField(max_length=50, verbose_name='descripcion')),
            ],
        ),
        migrations.DeleteModel(
            name='Habitacion',
        ),
        migrations.DeleteModel(
            name='Tipo_Habitacion',
        ),
    ]
