# Generated by Django 4.2.7 on 2023-11-19 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0011_hab_delete_habitacion_delete_tipo_habitacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='hab',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/'),
        ),
    ]
