# Generated by Django 4.2.6 on 2023-11-20 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0013_alter_hab_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hab',
            name='capacidad',
        ),
        migrations.RemoveField(
            model_name='hab',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='hab',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='hab',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='hab',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='hab',
            name='nro_hab',
        ),
        migrations.RemoveField(
            model_name='hab',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='hab',
            name='valor',
        ),
        migrations.AddField(
            model_name='hab',
            name='id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
