# Generated by Django 4.2.6 on 2023-11-20 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0014_remove_hab_capacidad_remove_hab_codigo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hab',
            name='nombre',
            field=models.CharField(default='', max_length=50, verbose_name='nombre'),
        ),
    ]
